// src/lib/components/ui/product/product-size.svelte
<script lang="ts">
	import type { StockAndSize } from '@prisma/client';
	import Button from '../button/button.svelte';
	import { currentSize } from '$lib/hooks/current-size.svelte';

	type ProductSizeProps = {
		sizes: StockAndSize[];
	};

	let { sizes }: ProductSizeProps = $props();
	currentSize.current = sizes[0];
	// Fungsi untuk mengubah ukuran yang dipilih
	const setSize = (size: StockAndSize) => {
		currentSize.current = size;
	};
</script>

<div class="flex flex-col space-y-2">
	<p class="text-lg font-semibold">
		Sizes •{' '}
		<span class="text-base text-muted-foreground">International</span>
	</p>
	<div class="flex flex-row flex-wrap gap-3">
		{#each sizes as size}
			<Button
				disabled={size.amount === 0}
				variant={currentSize.current.id === size.id ? 'default' : 'outline'}
				onclick={() => setSize(size)}>
				{size.name}
			</Button>
		{/each}
	</div>
</div>

// src/components/product/product-size.tsx
"use client";
import { Button } from "@/components/ui/button";
import { useSizes } from "@/hooks/use-sizes";
import { type StockAndSize } from "@prisma/client";
import React, { useEffect } from "react";

type Props = {
  sizes: StockAndSize[];
};

const ProductSizes = (props: Props) => {
  const { sizes, setSizes } = useSizes();

  useEffect(() => {
    setSizes(props.sizes.at(0));
  }, [props.sizes, setSizes]);

  return (
    <div className="flex flex-col space-y-2">
      <h3 className="text-lg font-semibold">
        Sizes •{" "}
        <span className="text-base text-muted-foreground">International</span>
      </h3>
      <div className="flex flex-row flex-wrap gap-3">
        {props.sizes.map((size) => (
          <Button
            key={size.id}
            disabled={size.amount === 0}
            variant={sizes?.id === size.id ? "default" : "outline"}
            onClick={() => setSizes(size)}
          >
            {size.name}
          </Button>
        ))}
      </div>
    </div>
  );
};

export default ProductSizes;
