// src/lib/components/ui/product/product-card.svelte
<script lang="ts">
	import { Image } from '@unpic/svelte';
	import * as Card from '$lib/components/ui/card/index.js';
	import ProductPrice from './product-price.svelte';
	import ProductRating from './product-rating.svelte';
	import type { ProductCardProps } from '$lib/types';

	let { product }: { product: ProductCardProps } = $props();
</script>

<!-- Tampilan komponen -->
<Card.Root class="relative rounded-2xl border p-2 shadow-lg">
	<a
		href={`/product/${product.slug}`}
		title={product.name}
		data-sveltekit-preload-data>
		<Image
			alt={product.name}
			src={product.image}
			width={200}
			height={300}
			layout="constrained"
			class="rounded-lg object-cover"
			background="data:image/bmp;base64,Qk1aBAAAAAAAADYAAAAoAAAABAAAAAMAAAABABgAAAAAACQAAAATCwAAEwsAAAAAAAAAAAAAzNbS7e7s0cvMcneGrrfBz9HasazCPUaNZnugg5O2g5HEE0qg" />

		<Card.CardContent
			class="relative mt-2 flex flex-col space-y-1 bg-background p-2">
			<Card.CardTitle
				class="w-[calc(100%-1px)] truncate text-[16px] font-normal leading-none">
				{product.name}
			</Card.CardTitle>
			<ProductRating rating={product.rating} />
			<ProductPrice
				price={product.price}
				discount={product.discount}
				priceAfterDiscount={product.priceAfterDiscount} />
		</Card.CardContent>
	</a>
</Card.Root>

// src/components/product/product-card.tsx
import React from "react";
import { Card, CardContent, CardTitle } from "@/components/ui/card";
import { type ProductCard as ProductCardProps } from "@/types";
import Link from "next/link";
import { Image } from "@unpic/react/nextjs";
import ProductPrice from "./product-price";
import ProductRating from "./product-rating";

type Props = {
  product: ProductCardProps;
};

const ProductCard = ({ product }: Props) => {
  return (
    <Card className="relative rounded-2xl border p-2 shadow-lg">
      <Link
        href={`/product/${product.slug}`}
        prefetch={true}
        title={product.name}
      >
        <Image
          alt={product.name}
          src={product.productImage.url}
          width={300}
          height={400}
          layout="constrained"
          className="rounded-lg object-cover"
        />
        <CardContent className="relative mt-4 space-y-2 bg-background p-2">
          <CardTitle className="w-[calc(100%-1px)] truncate text-[16px] font-normal leading-none">
            {product.name}
          </CardTitle>
          <ProductRating rating={product.rating} />
          <ProductPrice
            discount={product.discount}
            price={product.price}
            priceAfterDiscount={product.priceAfterDiscount}
            className="flex-grow"
          />
        </CardContent>
      </Link>
    </Card>
  );
};

export default ProductCard;
