// src/lib/components/ui/product/product-price.svelte
<script lang="ts">
	import { currentSize } from '$lib/hooks/current-size.svelte';
	import { cn } from '$lib/utils';

	type ProductPrice = {
		price: number;
		discount: number;
		priceAfterDiscount: number;
		priceClass?: string;
		discountClass?: string;
	};

	let { price, priceAfterDiscount, discount, priceClass, discountClass }: ProductPrice = $props();
</script>

<div class="inline-flex gap-2">
	{#if discount > 0}
		<p class={cn('font-bold', priceClass)}>${priceAfterDiscount}</p>
		<span class={cn('text-destructive line-through dark:text-red-500', discountClass)}
			>${price}</span
		>
	{:else}
		<p class={cn('font-bold', priceClass)}>${price}</p>
	{/if}
</div>

// src/components/product/product-price.tsx
import { cn } from "@/lib/utils";
import React, { type HTMLAttributes } from "react";

interface PriceProductProps extends HTMLAttributes<HTMLDivElement> {
  discount: number;
  price: number;
  priceAfterDiscount: number;
  priceClassName?: string;
  discountClassName?: string;
}

const ProductPrice = ({
  price,
  discount,
  className,
  priceClassName,
  discountClassName,
  priceAfterDiscount,
  ...props
}: PriceProductProps) => {
  return (
    <div
      className={cn(
        "flex items-center gap-2 text-sm lg:text-[16px]",
        className,
      )}
      {...props}
    >
      <div className={cn("font-bold", priceClassName)}>
        ${priceAfterDiscount}
      </div>
      {discount > 0 && (
        <p
          className={cn("text-sm text-red-600 line-through", discountClassName)}
        >
          ${price}
        </p>
      )}
    </div>
  );
};

export default ProductPrice;
